### ISSUE TITLE
Максимальная ширина медиа-контента

### ISSUE THREAD

**Issue by firefoxic** [web-standards-ru/web-standards.ru#155]
Заметил, что одни изображения нормально скейлятся под ширину контентной области, а другие уезжают под `overflow: hidden;` без возможности быть увиденными целиком.

Оказалось, что не помещаются те, что размечены синтаксисом md. А вставленные тегом `<img>` нормально ужимаются.
Изображения в md оборачиваются движком в тег `<p>`, из-за чего не попадают под действие стилей:
```css
/* Images */

.content > img,
.content > video,
.content figure > img,
.content figure > video,
.content a > img {
    display: block;
    max-width: 100%;
    height: auto;
    margin: 16px 0 8px;
}

@media (min-width: 1240px) {
    .content > img,
    .content > video {
        margin: 60px 0 60px auto;
    }
}
```
А других и нет. Вот и распирает их собственной "гордостью".

Вот пример — над одной из md-картинок вставил ту же самую картинку но просто тегом `<img>`:
![image](https://user-images.githubusercontent.com/3382798/99881707-4869ab80-2c2c-11eb-92df-4764457ff7fd.png)

Это баг? Или были какие-то планы на счёт этого?
