### ISSUE TITLE
Внедрить современный синтаксис медиавыражений

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/web-standards.ru#160]
Идея из ПР: https://github.com/web-standards-ru/web-standards.ru/pull/159/files#r549819244

**Comment by higimo** [comment]
@pepelsbey уточни, пжлст, речь о новом [стандарте 4 уровня](https://webref.ru/css/media)?
```css
@media (height > -100px) {
  body { background: green; }
}
```
