### ISSUE TITLE
Предложение по странице конференции

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/web-standards.ru#171]
![IMG_1429](https://user-images.githubusercontent.com/2804205/105254786-5d62ac80-5b93-11eb-9f8a-5c2d76030ae2.jpg)

С примерно таким набором данных:
```yml
name: Веб-стандарты 2020
dateStart: 2020-01-01
dateEnd: 2020-01-01
description: <div>10&nbsp;000 ₽</div>
program:
- - timeStart: 10:00
    timeEnd: 10:30
  - timeStart: 10:30
    timeEnd: 11:30
    speakers:
    - name: Вадим Макеев
      login: pepelsbey
      img: /%login%/avatar.jpg
    - name: Вадим Макеев
      login: pepelsbey
      img: /%login%/avatar.jpg
promotion: <div>...</div>
translation: <iframe>...</iframe>
registration: <a>...</a>
```
