### ISSUE TITLE
Страница статьи. Баг на большом разрешении

### ISSUE THREAD

**Issue by alkorlos** [web-standards-ru/web-standards.ru#33]
На разрешении 2560×1440 страница статьи выглядит так:
![article-bug](https://user-images.githubusercontent.com/14668230/80630559-7bb4d500-8a65-11ea-922c-12716658d30b.jpg)
Мешает правило
```css
@media (min-width: 1240px) {
  .article {
    display: grid;
    grid-template-rows: 1fr min-content;
    grid-template-columns: repeat(8, 1fr) calc(100vw - 1800px);
  }
}
```
Последняя колонка размером `calc(100vw - 1800px)`, видимо, служит для отступа справа на fullhd мониторах, но на > fullhd приводит к проблемам.
