### ISSUE TITLE
Внедрить box-sizing: border-box

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/web-standards.ru#79]
Я с большим удивлением обнаружил, что у нас нет такого файла:

```css
/* box-model.css */

*,
*::before,
*::after {
    box-sizing: border-box;
}
```

И в нескольких местах блочная модель вручную меняется. Такое стоит сделать умолчанием и проверить, ничего ли не сломалось.
